version: "3.8"

services:
  pg-admin-user-one:
    container_name: pgadmin-userone-bd2
    image: dpage/pgadmin4:4.10
    ports: 
      - ${PGADMIN_USER1_LISTEN_PORT}:${PGADMIN_USER1_REVERSE_EXPOSE_PORT}
    volumes: 
      - "bd2-volume:/var/lib/pgadmin-user1"
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_USER1_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_USER1_LISTEN_PORT}
    depends_on: 
      - postgres
    networks: 
      - pg-pgadmin-bd2
    restart: unless-stopped

  pg-admin-user-two:
    container_name: pgadmin-usetwo-bd2
    image: dpage/pgadmin4:4.10
    ports: 
      - ${PGADMIN_USER2_LISTEN_PORT}:${PGADMIN_USER2_REVERSE_EXPOSE_PORT}
    volumes: 
      - "bd2-volume:/var/lib/pgadmin-user2"
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_USER2_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_USER2_LISTEN_PORT}
    depends_on: 
      - postgres
    networks: 
      - pg-pgadmin-bd2
    restart: unless-stopped
